"""add category_id to faqs table

Revision ID: 0d781e87548f
Revises: e5fa9b202613
Create Date: 2026-03-01 21:59:37.339482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d781e87548f'
down_revision: Union[str, Sequence[str], None] = 'e5fa9b202613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_faqs_category_id'), 'faqs', ['category_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_faqs_category_id'), table_name='faqs')
    # ### end Alembic commands ###
