"""add ai_query_logs table

Revision ID: e5fa9b202613
Revises: 7ab796111868
Create Date: 2026-03-01 01:32:08.941557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5fa9b202613'
down_revision: Union[str, Sequence[str], None] = '7ab796111868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_query_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('results_returned', sa.Integer(), nullable=True),
    sa.Column('top_result_score', sa.Float(), nullable=True),
    sa.Column('escalated_to_forum', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_query_logs_id'), 'ai_query_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_query_logs_id'), table_name='ai_query_logs')
    op.drop_table('ai_query_logs')
    # ### end Alembic commands ###
