"""add_cognito_and_onboarding

Revision ID: 905904d64dfd
Revises: a87e65d9a702
Create Date: 2026-02-11 19:18:56.450258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '905904d64dfd'
down_revision: Union[str, Sequence[str], None] = 'a87e65d9a702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cognito_sub', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_onboarded', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_users_cognito_sub'), 'users', ['cognito_sub'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_cognito_sub'), table_name='users')
    op.drop_column('users', 'is_onboarded')
    op.drop_column('users', 'cognito_sub')
    # ### end Alembic commands ###
